weights: yolov5x.pt
cfg: models/yolov5x.yaml
data: data/ogsod_hbb_sar.yaml
hyp: data/hyp.cold_paper.yaml
epochs: 400
batch_size: 64
img_size:
- 256
- 256
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: /home/xmu/djd/ladd/cold_anchor/runs/ogsod_cold_terms
entity: null
name: cold_anchor_sar_yolov5x_v5p0_coco_nocold_coco_mixup010_e400_b64_5880ada
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: /home/xmu/djd/ladd/cold_anchor/runs/ogsod_cold_terms/cold_anchor_sar_yolov5x_v5p0_coco_nocold_coco_mixup010_e400_b64_5880ada
total_batch_size: 64
